// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZbhw8RyYFwCOwSTMVYcOvCed2WkCfcfU',
    appId: '1:189427299237:web:56890ff6976782454a6e4c',
    messagingSenderId: '189427299237',
    projectId: 'sena-ab01d',
    authDomain: 'sena-ab01d.firebaseapp.com',
    storageBucket: 'sena-ab01d.firebasestorage.app',
    measurementId: 'G-YHHVKBZJLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCITBPqfjyiB32D9dLUaygSH-Rib-iIO6c',
    appId: '1:189427299237:android:80fe7fbda461b4a24a6e4c',
    messagingSenderId: '189427299237',
    projectId: 'sena-ab01d',
    storageBucket: 'sena-ab01d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAMMgHhuxM9ZUQDCVmzMskvzXC7laalzI',
    appId: '1:189427299237:ios:de8871bf32caea3a4a6e4c',
    messagingSenderId: '189427299237',
    projectId: 'sena-ab01d',
    storageBucket: 'sena-ab01d.firebasestorage.app',
    iosBundleId: 'com.example.sena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAMMgHhuxM9ZUQDCVmzMskvzXC7laalzI',
    appId: '1:189427299237:ios:4b2a8fe4a5310af84a6e4c',
    messagingSenderId: '189427299237',
    projectId: 'sena-ab01d',
    storageBucket: 'sena-ab01d.firebasestorage.app',
    iosBundleId: 'com.acodr.sena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZbhw8RyYFwCOwSTMVYcOvCed2WkCfcfU',
    appId: '1:189427299237:web:91959de3f52d52634a6e4c',
    messagingSenderId: '189427299237',
    projectId: 'sena-ab01d',
    authDomain: 'sena-ab01d.firebaseapp.com',
    storageBucket: 'sena-ab01d.firebasestorage.app',
    measurementId: 'G-PWELK47Y79',
  );
}
