import 'package:flutter/material.dart';
import '../models/models.dart';

/// Mock seed data for all entities
class MockData {
  static final List<WorkerModel> workers = [
    WorkerModel(
      id: 'w1',
      fullName: 'Raju Sharma',
      age: 28,
      aadhaarNumber: '1234 5678 9012',
      skills: ['Mason', 'Plastering', 'Tiling'],
      yearsOfExperience: 5,
      city: 'Pune',
      state: 'Maharashtra',
      phone: '9876543210',
      email: 'raju.sharma@example.com',
      availability: AvailabilityStatus.available,
      languages: ['Hindi', 'Marathi'],
    ),
    WorkerModel(
      id: 'w2',
      fullName: 'Suresh Kumar',
      age: 35,
      aadhaarNumber: '9876 5432 1098',
      skills: ['Electrician', 'Wiring', 'Panel Fitting'],
      yearsOfExperience: 10,
      city: 'Mumbai',
      state: 'Maharashtra',
      phone: '9123456789',
      email: 'suresh.kumar@example.com',
      availability: AvailabilityStatus.available,
      languages: ['Hindi', 'English'],
      contractorId: 'c1',
    ),
    WorkerModel(
      id: 'w3',
      fullName: 'Meena Devi',
      age: 30,
      aadhaarNumber: '5678 1234 3456',
      skills: ['Painter', 'Wall Putty', 'Texture Work'],
      yearsOfExperience: 4,
      city: 'Nagpur',
      state: 'Maharashtra',
      phone: '9988776655',
      email: 'meena.devi@example.com',
      availability: AvailabilityStatus.unavailable,
      languages: ['Hindi', 'Marathi'],
      contractorId: 'c1',
    ),
    WorkerModel(
      id: 'w4',
      fullName: 'Arun Patel',
      age: 22,
      aadhaarNumber: '1111 2222 3333',
      skills: ['Helper', 'Loading/Unloading', 'Housekeeping'],
      yearsOfExperience: 1,
      city: 'Surat',
      state: 'Gujarat',
      phone: '8877665544',
      email: 'arun.patel@example.com',
      availability: AvailabilityStatus.available,
      languages: ['Gujarati', 'Hindi'],
    ),
    WorkerModel(
      id: 'w5',
      fullName: 'Vijay Tiwari',
      age: 40,
      aadhaarNumber: '4444 5555 6666',
      skills: ['Plumber', 'Pipe Fitting', 'Sanitary Works'],
      yearsOfExperience: 15,
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      phone: '7766554433',
      email: 'vijay.tiwari@example.com',
      availability: AvailabilityStatus.available,
      languages: ['Hindi'],
      contractorId: 'c2',
    ),
  ];

  static final List<ContractorModel> contractors = [
    ContractorModel(
      id: 'c1',
      fullName: 'Ramesh Gupta',
      age: 45,
      aadhaarNumber: '2222 3333 4444',
      phone: '9000011111',
      email: 'ramesh.gupta@example.com',
      businessName: 'Gupta Construction Services',
      city: 'Mumbai',
      state: 'Maharashtra',
      availability: AvailabilityStatus.available,
    ),
    ContractorModel(
      id: 'c2',
      fullName: 'Priya Singh',
      age: 38,
      aadhaarNumber: '3333 4444 5555',
      phone: '9000022222',
      email: 'priya.singh@example.com',
      businessName: 'Singh Labour Suppliers',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      availability: AvailabilityStatus.available,
    ),
  ];

  static final List<CompanyModel> companies = [
    CompanyModel(
      id: 'co1',
      companyName: 'BuildRight Pvt. Ltd.',
      gstNumber: '27AAABZ1234C1Z5',
      address: '12, Industrial Area, Andheri East, Mumbai',
      authorizedPersonName: 'Nitin Mehta',
      designation: 'HR Manager',
      email: 'hr@buildright.in',
      phone: '9100000001',
      description: 'Leading construction company in Western India.',
      industryType: 'Construction',
    ),
    CompanyModel(
      id: 'co2',
      companyName: 'QuickFix Solutions',
      gstNumber: '24BBBCZ5678D2Y3',
      address: '45, Tech Park, Whitefield, Bengaluru',
      authorizedPersonName: 'Anita Rao',
      designation: 'Operations Head',
      email: 'ops@quickfix.in',
      phone: '9100000002',
      description: 'Facility management and maintenance services.',
      industryType: 'Facility Management',
    ),
  ];

  static List<HiringRequest> hiringRequests = [
    HiringRequest(
      id: 'hr1',
      companyId: 'co1',
      companyName: 'BuildRight Pvt. Ltd.',
      contractorId: 'c1',
      workersRequired: 5,
      skillRequired: 'Mason',
      standardWage: 600,
      offeredWage: 650,
      duration: WorkDuration.monthly,
      workLocation: 'Andheri East, Mumbai',
      startDate: DateTime(2026, 3, 10),
      additionalRequirements: 'Should have experience in plastering.',
      status: RequestStatus.pending,
      createdAt: DateTime(2026, 3, 1),
    ),
    HiringRequest(
      id: 'hr2',
      companyId: 'co1',
      companyName: 'BuildRight Pvt. Ltd.',
      workerId: 'w4',
      workersRequired: 1,
      skillRequired: 'Helper',
      standardWage: 400,
      offeredWage: 420,
      duration: WorkDuration.daily,
      workLocation: 'Bandra, Mumbai',
      startDate: DateTime(2026, 3, 8),
      status: RequestStatus.accepted,
      createdAt: DateTime(2026, 2, 28),
    ),
    HiringRequest(
      id: 'hr3',
      companyId: 'co2',
      companyName: 'QuickFix Solutions',
      contractorId: 'c2',
      workersRequired: 3,
      skillRequired: 'Plumber',
      standardWage: 700,
      offeredWage: 720,
      duration: WorkDuration.yearly,
      workLocation: 'Whitefield, Bengaluru',
      startDate: DateTime(2026, 4, 1),
      additionalRequirements: 'Must know sanitary fitting.',
      status: RequestStatus.pending,
      createdAt: DateTime(2026, 2, 25),
    ),
  ];

  static List<AppNotification> notifications = [
    AppNotification(
      id: 'n1',
      title: 'New Hiring Request',
      message: 'BuildRight Pvt. Ltd. sent you a hiring request for 5 Masons.',
      time: DateTime(2026, 3, 1, 10, 30),
    ),
    AppNotification(
      id: 'n2',
      title: 'Request Accepted',
      message: 'Arun Patel accepted your hiring request for Helper role.',
      time: DateTime(2026, 2, 28, 15, 0),
      isRead: true,
    ),
    AppNotification(
      id: 'n3',
      title: 'New Hiring Request',
      message: 'QuickFix Solutions wants 3 Plumbers from Singh Labour Suppliers.',
      time: DateTime(2026, 2, 25, 9, 0),
      isRead: true,
    ),
  ];
}
